# Generated by Django 5.0.6 on 2024-07-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_chapter_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
