# Generated by Django 5.0.6 on 2024-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassignment",
            name="student_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
