# Generated by Django 5.0.6 on 2024-07-18 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_studentassignment_student_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField()),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.CreateModel(
            name="CourseQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_quizzes",
                        to="main.course",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_courses",
                        to="main.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Quiz",
            },
        ),
        migrations.CreateModel(
            name="QuizQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.CharField(max_length=200)),
                ("ans1", models.CharField(max_length=200)),
                ("ans2", models.CharField(max_length=200)),
                ("ans3", models.CharField(max_length=200)),
                ("ans4", models.CharField(max_length=200)),
                ("right_ans", models.CharField(max_length=200)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quiz Questions",
            },
        ),
    ]
